console.log("Первое задание");
let str;
str = "Hello";
let num;
num = 123;
let flag;
flag = true;
let txt;
txt = "true";
console.log(typeof str);
console.log(typeof num);
console.log(typeof flag);
console.log(typeof txt);