console.log("Второе задание");
let a;
a = "Hello world";
let bakaran;
bakaran = 123;
let cypher;
cypher = true;
let obs;
obs = "true";
const ab;
ab = "Hi world";
const narakab;
narakab = 321;
const cipher;
cipher = true;
const failure;
failure = "true";
let bandi;
bandi = false;
const obstacle;
obstacle = false;